name: Publish on main

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "tsup.config.ts"
      - "tsconfig.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Skip if version already exists
        id: skip
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VER=$(node -p "require('./package.json').version")
          PUBLISHED=$(npm view "$PKG_NAME@${PKG_VER}" version || true)
          if [ "$PUBLISHED" = "$PKG_VER" ]; then
            echo "already=true" >> "$GITHUB_OUTPUT"
          else
            echo "already=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish
        if: steps.skip.outputs.already == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        run: npm publish --access public
